[project]
name = "m3u82vlc"
version = "0.1.0"
description = "Simple m3u8 stream detector with vlc backed playback&recording functionality"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mitmproxy>=11.1.0",
    "selenium>=4.27.1",
]
